action: Send to URL
attack:
    type: xss
payload:
    method: Auto
    encoding: ""
    source: Auto
    file_path: ""
    custom: []
evasion:
    level: Medium
target:
    method: URL
    url: http://example.com/vulnerable-page
report:
    type: HTML
    auto: true
