version: '3.8'

services:
  echoserver:
    image: piyushroshan/echo-server:arm64
    ports:
      - "7080:8080"
  
  corazacaddy:
    image: piyushroshan/coraza-caddy:arm64
    depends_on:
      - echoserver
    volumes:
      - ./logs:/app/logs
    ports:
      - "8888:8000"

  obfuskit:
    image: piyushroshan/obfuskit:arm64
    depends_on:
      - corazacaddy
    environment:
      - OBFUSKIT_MODE=server
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output:rw
    ports:
      - "8181:8181"
