version: '3.8'

services:
  echoserver:
    image: piyushroshan/echo-server:latest
    ports:
      - "7080:8080"

  vulnapp:
    image: piyushroshan/obfuskit-vuln-app:latest
    ports:
      - "8889:8881"
  
  corazacaddy:
    image: piyushroshan/obfuskit-coraza-waf:latest
    depends_on:
      - echoserver
    volumes:
      - ./logs:/app/logs
    ports:
      - "8888:8000"
      - "8881:8881"
      - "8882:8882"

  obfuskit:
    image: piyushroshan/obfuskit:latest
    depends_on:
      - corazacaddy
    environment:
      - OBFUSKIT_MODE=server
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output:rw
    ports:
      - "8181:8181"
