name: PR Build (Go, amd64/arm64)

on:
  pull_request:
    branches:
      - main
  
env:
  GO_VERSION: '1.23.4'
  BINARY_NAME: 'obfuskit'
  JDK_DISTRIBUTION: 'temurin'
  JDK_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
        goos: [linux]
    name: Build (${{ matrix.goos }}/${{ matrix.goarch }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v ./... -o ${{ env.BINARY_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Validate binary
        run: |
          ./${{ env.BINARY_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }} --help

      - name: Run tests
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go test -v ./...

  burp-plugin:
    runs-on: ubuntu-latest
    name: Build Burp Plugin (Gradle)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}

      - name: Build with Gradle
        run: |
          ./gradlew build
        working-directory: ./integrations/burpplugin